system:
  ip: ""
  port: 8080
  env: dev
  gin_mode: debug
log:
  app: blogx_server
  dir: logs
jwt:
  expire: 24
  secret: lmr-blogx-2026
  issuer: lmr
redis:
  addr: 123.57.220.143:6379
  password: 199107Lmr1636
  db: 0
upload:
  size: 1
  whiteList:
  - jpg
  - jpeg
  - png
  - webp
  - gif
  uploadDir: images001
db:
  user: root
  password: 123456
  host: 118.25.141.36
  port: 3306
  db: blogx
  debug: false
  source: mysql
db2:
  user: root
  password: 123456
  host: 118.25.141.36
  port: 3307
  db: blogx
  debug: false
  source: mysql
es:
  url: http://118.25.141.36:9200
  username:
  password:
site:
  siteInfo:
    title: 这是站点标题
    logo: ""
    beian: ""
    mode: 1
  project:
    title: 这是新的title6
    icon: /yyy.png
    webPath: demos/index.html
  seo:
    keywords: kkk
    description: ddd
  about:
    siteAbout: ""
    qq: ""
    wechat: ""
    gitee: ""
    bilibili: ""
    github: ""
  login:
    qqLogin: false
    usernamePwdLogin: true
    emailPwdLogin: true
    captcha: false
  indexRight:
    list: []
  article:
    noExamine: false
email:
  domain: smtp.qq.com
  port: 587
  sendEmail: 1172778182@qq.com
  authCode: cvjtoycgcjyvfegh
  sendNickname: blogx
  ssl: false
  tls: false
qq:
  appID: ""
  appKey: ""
  redirect: ""
qiNiu:
  enable: true
  accessKey: dXTDkYpO_JTOp8bnU0U1OGDkYO1U2CKdig40pG1l
  secretKey: smgJke38uz3t2MTZcBQt7usEdTQO_ILEagMKmDe2
  bucket: limingru-blogx
  uri: http://cdn.limingru.com
  region: z2
  prefix: blogx
  size: 3
  expiry: 60
ai:
  enable: true
  secretKey: ""
  nickname: ""
  avatar: ""
